### ISSUE TITLE
Add snip that merges 2 or more objects

### ISSUE THREAD

**Issue by DevTMK** [DevTMK/snips#29]
If there are the same keys in the objects and the first value is not a primitive data type, then it should merge also

**Comment by GaurKS** [comment]
Can you give a sample testcase that will satisfy the condition for better understanding?

**Comment by DevTMK** [comment]
Like E.g.-
merge({ a: [1,2,3], b: 1 }, { a: 4, c: 'bar' }) 
The output will be - `{ a: [1,2,3,4], b: 1, c: 'bar' }`
And if the `a` is a primitive value it will be replaced by the overlapping value

Tell me if u need more details @GaurKS

**Comment by MahmoudDawood** [comment]
@DevTMK I would love to work on this issue if GaurKS is not working on it.

Is it ok to suggest frequently needed snips in issues or do you pick specific ones?

**Comment by DevTMK** [comment]
You can work on it @MahmoudDawood, first right PR will be accepted

And yes you can create issues for new snip ideas or changes
