### ISSUE TITLE
Add snip that returns a time difference between input and current time in proper format

### ISSUE THREAD

**Issue by DevTMK** [DevTMK/snips#41]
E.g. timeDiff("2022-10-27 17:30:00")
If suppose the current time is `17:35`
then the output should be `5 minutes`

If the current time is `18:35`
output: `1 hour 5 minutes`

**Comment by MahmoudDawood** [comment]
That seems interesting to work on!
Could I get this issue assigned to me?

**Comment by DevTMK** [comment]
Sure @MahmoudDawood
